# str="python"
# print(max(str))
# print(min(str))
# print(len(str))
# print(id(str))
# print(type(str))
# print(ord('A'))
# print(ord('Z'))
# print(ord('a'))
# print(ord('z'))
# print(ord(' '))
# print(ord('0'))
# print(chr(32))
# print(chr(49))
# print(chr(64))
# print(chr(78))
# x=input()
sr1='I love python'
print(sr1.lower())
print(sr1.upper())
print(sr1.swapcase())
print(sr1.title())
print(sr1.capitalize())
print(sr1.count('o'))
print(sr1.index('p'))
# print(sr1.index('P'))# error substring not found
print(sr1.find('P'))